version: "3.8"

services:
  # MYSQL
  db:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rdOCR
      MYSQL_DATABASE: openocrdb
      MYSQL_USER: dba
      MYSQL_PASSWORD: dbaPass

#  adminer:
#    image: adminer
#    container_name: database_adminer
#    restart: always
#    ports:
#      - 8080:8080

volumes:
  data: {}
networks:
  default:
    name: openOCR_database_default
